### ISSUE TITLE
Container decoration

### ISSUE THREAD

**Issue by AxanIqbal** [flutter-form-builder-ecosystem/form_builder_image_picker#25]
can you able to give more customization on the preview container and it would be better if we customize the bottom sheet or choose between dialog or sheet

**Comment by deandreamatias** [comment]
Because currently I don't have time to develop specifically feature like this, we only focus on resolve and maintain the package with minimal functionality.
I recommend that implement your own FormField in this case. Take a look on [this](https://medium.com/@danvickmiller/turn-any-flutter-widget-into-a-form-input-c23223042e3b)
